categories_data_structure = {
    "immobilier": {
        "titre": "str",
        "url": "str",
        "site_origine": "str",
        "categorie": "str",
        "category": "str",
        "date_crawl": "str (ISO date)",
        "prix": "str",
        "prix_unit": "str",
        "prix_value": "str",
        "prix_dec": "float/str",
        "description": "str",
        "bien": "str",
        "numero": "str",
        "date_depot": "str (ISO date)",
        "nombre_vues": "str",
        "nb_pieces": "int/str",
        "superficie": "str",
        "superficie_unit": "str",
        "papiers": "list (str)",
        "specifications": "list (str)",
        "images": "list (str)",
        "etage": "str",
        "transaction": "str",
        "payment": "list (str)",
        "adresse": "str",
        "wilaya": "str",
        "commune": "str",
        "status": "str",
        "contact": {
            "name": "str/None",
            "profile_link": "str/None",
            "email": "list (str)",
            "phones": "list (str)",
            "whatsapp": "list (str)",
            "telegram": "list (str)",
            "viber": "list (str)"
        },
        "as_photo": "str",
        "date_verif": "str (ISO date)",
        "as_prix": "str"
    },
    "voiture": {
        "titre": "str",
        "description": "str",
        "numero": "str",
        "nombre_vues": "str",
        "date_depot": "str (ISO date)",
        "site_origine": "str",
        "categorie": "str",
        "category": "str",
        "images": "list (str)",
        "url": "str",
        "annee": "str",
        "marque": "str",
        "model": "str",
        "finition": "str",
        "prix": "str",
        "prix_unit": "str",
        "prix_value": "str",
        "prix_condition": "str",
        "prix_dec": "float/int",
        "adresse": "str",
        "wilaya": "str",
        "commune": "str",
        "etat": "str",
        "date_crawl": "str (ISO date)",
        "status": "str",
        "as_photo": "str",
        "as_prix": "str",
        "km": "str",
        "km_unit": "str",
        "moteur": "str",
        "papers": "str",
        "couleur": "str",
        "options": "list (str)",
        "energie": "str",
        "transmission": "str",
        "contact": {
            "name": "str/None",
            "profile_link": "str/None",
            "email": "list (str)",
            "phones": "list (str)",
            "whatsapp": "list (str)",
            "telegram": "list (str)",
            "viber": "list (str)"
        }
    },
    "emploi": {
        "titre": "str",
        "url": "str",
        "site_origine": "str",
        "categorie": "str",
        "category": "str",
        "date_crawl": "str (ISO date)",
        "niveau": "str",
        "numero": "str",
        "date_depot": "str (ISO date)",
        "nombre_vues": "str",
        "transaction": "str",
        "description": "str",
        "employeur": "str",
        "adresse": "str",
        "wilaya": "str",
        "commune": "str",
        "status": "int",
        "date_verif": "str (ISO date)",
        "images": "list (str)",
        "as_photo": "str",
        "as_prix": "str",
        "vehicle": "str (bool-like)",
        "prix": "str",
        "prix_unit": "str",
        "prix_value": "str",
        "prix_dec": "float/str",
        "contact": {
            "name": "str/None",
            "profile_link": "str/None",
            "email": "list (str)",
            "phones": "list (str)",
            "whatsapp": "list (str)",
            "telegram": "list (str)",
            "viber": "list (str)"
        }
    },
    "electromenager": {
        "titre": "str",
        "url": "str",
        "etat": "str",
        "livraison": "str",
        "site_origine": "str",
        "transaction": "str",
        "category": "str",
        "categorie": "str",
        "description": "str",
        "date_depot": "str",
        "marque": "str",
        "modele": "str",
        "garantie": "str",
        "garantie_unit": "str",
        "poid": "str",
        "poid_unit": "str",
        "couleur": "str",
        "batterie": "str",
        "prix_dec": "str",
        "prix_unit": "str",
        "images": "list (str)",
        "adresse": "str",
        "status": "int",
        "date_crawl": "str (ISO date)",
        "date_verif": "str (ISO date)",
        "as_photo": "str",
        "as_prix": "str",
        "contact": {
            "name": "str/None",
            "profile_link": "str/None",
            "email": "list (str)",
            "phones": "list (str)",
            "whatsapp": "list (str)",
            "telegram": "list (str)",
            "viber": "list (str)"
        },
        "par_facilite": "str (optional)",
        "prix_facilite": "dict (optional)",
        "premier_versement": "str (optional)",
        "premier_versement_value": "str (optional)"
    },
    "multimedia": {
        "titre": "str",
        "url": "str",
        "etat": "str",
        "livraison": "str",
        "site_origine": "str",
        "transaction": "str",
        "category": "str",
        "categorie": "str",
        "description": "str",
        "date_depot": "str",
        "marque": "str",
        "modele": "str",
        "garantie": "str",
        "garantie_unit": "str",
        "dimension": "str/list",
        "dimension_unit": "str/list",
        "type_ecran": "str",
        "taille_ecran": "str",
        "taille_ecran_unit": "str",
        "os": "str",
        "os_version": "str",
        "poid": "str",
        "poid_unit": "str",
        "couleur": "str",
        "processor_cores": "str",
        "processor_hz": "str",
        "m_interne": "str",
        "m_interne_unit": "str",
        "ram": "str",
        "ram_unit": "str",
        "camera_ar": "str",
        "camera_av": "str",
        "batterie": "str",
        "prix_dec": "str",
        "prix_unit": "str",
        "images": "list (str)",
        "adresse": "str",
        "status": "int",
        "date_crawl": "str (ISO date)",
        "date_verif": "str (ISO date)",
        "as_photo": "str",
        "as_prix": "str",
        "contact": {
            "name": "str/None",
            "profile_link": "str/None",
            "email": "list (str)",
            "phones": "list (str)",
            "whatsapp": "list (str)",
            "telegram": "list (str)",
            "viber": "list (str)"
        },
        "par_facilite": "str",
        "prix_facilite": "dict",
        "premier_versement": "str",
        "premier_versement_value": "str"
    }
}
